# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_management
spring.datasource.username=postgres
spring.datasource.password=ROOT

# Hibernate Configuration (Automatically creates/updates your database tables)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Set the server port (Default is 8080)
server.port=8080